server:
  port: 80
  servlet:
    path: /
logging:
  level:
    com.wenxin: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edu?characterEncoding=UTF-8
    username: root
    password: 123456
mybatis:
 # mapper-locations: mapper/*.xml
  type-aliases-package: com.wenxin.pojo